
using Microsoft.Build.Framework;
using System;
using System.ComponentModel.DataAnnotations.Schema;
namespace CodingTest.Models { 

    // Table containing text/images that will be displayed on webpage
    // each row has a timestamp with the text/image that has been changed
    // displays row with most recent timestamp
    // allows for storage of previous versions
    public class Elements
    {
     
        public  int id { get; set; }

        public  String? Panal1Title { get; set; }
        public  String? Panal2Title { get; set; }
        public  String? Panal2Text { get; set; }
        public  String? Panal3Title { get; set; }
        public  String? Panal3ImageTitle1 { get; set; }

        public  String? Panal3ImageTitle2 { get; set; }
        public  String? Panal3ImageTitle3 { get; set; }

        public  String? Panal3ImageText1 { get; set; }
        public  String? Panal3ImageText2 { get; set; }
        public  String? Panal3ImageText3 { get; set; }

        public  String? Panal4Title { get; set; }
        public  String? Panal4Text { get; set; }
        public  String? Panal1Image { get; set; }

        // Version is autogenerated
        public  int Version { get; set; }




    }





}
