// <auto-generated />
using CodingTest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodingTest.Migrations
{
    [DbContext(typeof(ElementsContext))]
    [Migration("20240830195025_AlterVersion")]
    partial class AlterVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CodingTest.Models.Elements", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Panel1Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panel1Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panel1Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panel2Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panel2Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panel3ImageText1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panel3ImageText2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panel3ImageText3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panel3ImageTitle1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panel3ImageTitle2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panel3ImageTitle3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panel3Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panel4Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panel4Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
