// <auto-generated />
using CodingTest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodingTest.Migrations
{
    [DbContext(typeof(ElementsContext))]
    partial class ElementsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CodingTest.Models.Elements", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Panal1Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panal1Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panal2Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panal2Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panal3ImageText1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panal3ImageText2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panal3ImageText3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panal3ImageTitle1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panal3ImageTitle2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panal3ImageTitle3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panal3Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panal4Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Panal4Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
